name: deep_momentum_networks
channels:
  - defaults
dependencies:
  - python==3.11.4
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - seaborn
  - pyarrow
  - joblib
  - statsmodels
  - pyyaml=5.4.1
  - matplotlib
  - tqdm
  - jupyter
  - notebook
  - pip
  - pip:
    - torch
    - empyrical
    - optuna
    - captum
